Repository boostcampwm-2021/android02-mowoori, pull requests merged in 2021-11, with the labels that each got.

#16 [4-3] 네비게이션 드로우어 추가
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/res/drawable/ic_hamburger.xml
  app/src/main/res/layout/fragment_home.xml
Labels: pull request, feat, ❄️ kldaji

#30 [5-1] 드로우어 헤더 추가 및 초대 여부 화면 이동
  app/src/main/java/com/ariari/mowoori/ui/group/InviteCheckFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_invite_check.xml
  app/src/main/res/layout/header_navigation_drawer.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: pull request, feat, ❄️ kldaji

#31 [4-1] 눈내리는 애니메이션 추가
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/res/drawable/ic_snow.xml
  app/src/main/res/layout/fragment_home.xml
Labels: feat, layout, ⛄hyo

#32 [5-2] 그룹 목록 조회
  .gitignore
  app/src/main/java/com/ariari/mowoori/ui/group/InviteCheckFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/adapter/DrawerAdapter.kt
  app/src/main/java/com/ariari/mowoori/ui/home/adapter/DrawerAdapterDecoration.kt
  app/src/main/java/com/ariari/mowoori/ui/home/entity/Group.kt
  app/src/main/java/com/ariari/mowoori/ui/main/MainActivity.kt
  app/src/main/res/drawable/border_sky_blue_fill_16.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/header_navigation_drawer.xml
  app/src/main/res/layout/item_drawer_group.xml
  app/src/main/res/layout/item_drawer_header.xml
  app/src/main/res/values/strings.xml
Labels: pull request, feat, ❄️ kldaji

#33 [4-1] 눈사람 애니메이션 수정 및 코루틴 적용
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ariari/mowoori/App.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/home/SnowmanLevel.kt
  app/src/main/java/com/ariari/mowoori/util/TimberUtil.kt
  app/src/main/res/animator/animator_snow_down.xml
  app/src/main/res/animator/animator_snow_up.xml
  app/src/main/res/drawable/ic_snow_face.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: fix, pull request, feat, ⛄hyo

#34 [7-1] 그룹 추가 옵션 화면 이동
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/ariari/mowoori/ui/group/GroupNameFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/group/InviteCheckFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/group/InviteCodeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/res/drawable/border_sky_blue_line_24.xml
  app/src/main/res/layout/fragment_group_name.xml
  app/src/main/res/layout/fragment_invite_check.xml
  app/src/main/res/layout/fragment_invite_code.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/strings.xml
Labels: pull request, feat, layout, ❄️ kldaji

#35 [0-1] 상단바 커스텀뷰 제작
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ariari/mowoori/ui/custom/CustomTitleView.kt
  app/src/main/java/com/ariari/mowoori/ui/custom/SampleTitleViewActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/custom/SampleViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/custom/TitleViewMode.kt
  app/src/main/java/com/ariari/mowoori/util/BindingAdapters.kt
  app/src/main/java/com/ariari/mowoori/util/Event.kt
  app/src/main/java/com/ariari/mowoori/util/EventObserver.kt
  app/src/main/java/com/ariari/mowoori/util/ToastMessageUtil.kt
  app/src/main/res/drawable/ic_title_view_back.xml
  app/src/main/res/drawable/ic_title_view_close.xml
  app/src/main/res/drawable/ic_title_view_plus.xml
  app/src/main/res/layout/activity_sample_title_view.xml
  app/src/main/res/layout/custom_title_view.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
Labels: pull request, feat, layout, 🍇yjooooo

#36 [1-1] 스플래쉬 & 로그인 화면
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ariari/mowoori/App.kt
  app/src/main/java/com/ariari/mowoori/ui/splash/SignInIntentContract.kt
  app/src/main/java/com/ariari/mowoori/ui/splash/SplashActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/splash/SplashViewModel.kt
  app/src/main/res/drawable-hdpi/ic_logo.png
  app/src/main/res/drawable-mdpi/ic_logo.png
  app/src/main/res/drawable-xhdpi/ic_logo.png
  app/src/main/res/drawable-xxhdpi/ic_logo.png
  app/src/main/res/drawable-xxxhdpi/ic_logo.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feat, layout, 💡light

#37 [4-1] 눈사람 애니메이션 추가 및 상단바 메뉴 추가
  app/build.gradle
  app/src/main/assets/lottie-sun.json
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/res/animator/animator_snow_down.xml
  app/src/main/res/animator/animator_snow_move_horizontal.xml
  app/src/main/res/animator/animator_snow_up.xml
  app/src/main/res/drawable/ic_alarm.xml
  app/src/main/res/drawable/ic_home_sun.xml
  app/src/main/res/drawable/ic_snow_face_2.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/menu/tb_home_menu.xml
  build.gradle
Labels: fix, build, pull request, feat, layout, ⛄hyo

#39 [17-1] Hilt 적용
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ariari/mowoori/MoWooriApp.kt
  app/src/main/java/com/ariari/mowoori/data/repository/IntroRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/IntroRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/di/FirebaseModule.kt
  app/src/main/java/com/ariari/mowoori/di/RepositoryModule.kt
  app/src/main/java/com/ariari/mowoori/ui/group/GroupNameFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/group/InviteCheckFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/group/InviteCodeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/intro/SignInIntentContract.kt
  app/src/main/java/com/ariari/mowoori/ui/main/MainActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/members/MembersFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsFragment.kt
  app/src/main/res/layout/activity_intro.xml
  build.gradle
Labels: pull request, feat, 🍇yjooooo, ❄️ kldaji, ⛄hyo, 💡light

#41 [4-2] 홈화면 -> 알림화면 이동 기능 구현
  app/build.gradle
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/notification/NotificationFragment.kt
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/strings.xml
Labels: build, pull request, feat, ⛄hyo

#42 [11-1] 미완료, 완료, 실패 카테고리에 따른 미션 리스트 조회
  app/src/main/java/com/ariari/mowoori/ui/custom/SampleTitleViewActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/custom/SampleViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/adapter/MissionsAdapter.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/entity/Mission.kt
  app/src/main/res/drawable/border_sky_blue_fill_10.xml
  app/src/main/res/layout/activity_sample_title_view.xml
  app/src/main/res/layout/custom_title_view.xml
  app/src/main/res/layout/fragment_missions.xml
  app/src/main/res/layout/item_missions.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: pull request, feat, layout, 🍇yjooooo

#43 4 register nickname
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ariari/mowoori/data/repository/IntroRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/IntroRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/di/FirebaseModule.kt
  app/src/main/java/com/ariari/mowoori/di/RepositoryModule.kt
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/register/entity/User.kt
  app/src/main/res/drawable/ic_profile_empty.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: feat, 💡light

#44 [11-2] 미션 생성 화면으로 이동
  app/src/main/java/com/ariari/mowoori/ui/main/MainActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions_add/MissionsAddFragment.kt
  app/src/main/res/layout/fragment_missions_add.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/strings.xml
Labels: pull request, feat, 🍇yjooooo

#46 Feature/3 register profile
  app/src/main/java/com/ariari/mowoori/data/repository/IntroRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/IntroRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/register/entity/User.kt
  app/src/main/java/com/ariari/mowoori/util/BindingAdapters.kt
  app/src/main/java/com/ariari/mowoori/widget/ProgressDialogManager.kt
  app/src/main/res/drawable/ic_snow_head.xml
  app/src/main/res/drawable/rotate_progress.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/dialog_progress.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feat, 💡light

#47 [5-2] 그룹 변경
  .gitignore
  app/build.gradle
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/home/adapter/DrawerAdapter.kt
  app/src/main/java/com/ariari/mowoori/ui/home/entity/Group.kt
  app/src/main/java/com/ariari/mowoori/ui/register/entity/User.kt
  app/src/main/res/drawable/border_transparent_fill.xml
  app/src/main/res/values/colors.xml
  build.gradle
Labels: pull request, feat, ❄️ kldaji

#48 #21 fix: 나의 미션 탭 화면 이동 후 돌아왔을 시 미션 타입 유지되도록 수정
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsFragment.kt
  app/src/main/res/layout/fragment_missions.xml
Labels: fix, pull request, 🍇yjooooo

#52 [2-2] 예/아니오 다이얼로그 생성
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterViewModel.kt
  app/src/main/java/com/ariari/mowoori/widget/BaseDialogFragment.kt
  app/src/main/java/com/ariari/mowoori/widget/ConfirmDialogFragment.kt
  app/src/main/java/com/ariari/mowoori/widget/ProgressDialogManager.kt
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/dialog_confirm.xml
Labels: pull request, feat, ❄️ kldaji

#53 [11-1] 미션 리스트 파이어베이스에서 받아와서 표시
  .idea/runConfigurations.xml
  app/src/main/java/com/ariari/mowoori/data/repository/MissionsRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/MissionsRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/di/RepositoryModule.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/entity/Mission.kt
  app/src/main/java/com/ariari/mowoori/util/Util.kt
Labels: pull request, feat, ⛄hyo

#55 [18-1] BaseActivity, BaseFragment 추가
  app/src/main/java/com/ariari/mowoori/base/BaseActivity.kt
  app/src/main/java/com/ariari/mowoori/base/BaseFragment.kt
Labels: pull request, feat, 🍇yjooooo

#56 [13-1] 스탬프 프래그먼트 생성
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/entity/Stamp.kt
  app/src/main/res/drawable/border_black_line.xml
  app/src/main/res/drawable/border_sky_blue_line_oval.xml
  app/src/main/res/layout/fragment_stamps.xml
  app/src/main/res/layout/item_stamps.xml
  app/src/main/res/values/strings.xml
Labels: pull request, layout, ❄️ kldaji

#57 [11-1] 미션 아이템 클릭 리스너 추가
  app/build.gradle
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/adapter/MissionsAdapter.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/entity/Mission.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsFragment.kt
  app/src/main/res/layout/item_missions.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: build, pull request, feat, ⛄hyo

#58 [2-2] 다이얼로그 백그라운드 변경
  app/src/main/java/com/ariari/mowoori/widget/BaseDialogFragment.kt
  app/src/main/res/drawable/border_sky_blue_line_30.xml
  app/src/main/res/drawable/border_white_fill_16.xml
  app/src/main/res/layout/dialog_confirm.xml
  app/src/main/res/layout/fragment_group.xml
  app/src/main/res/layout/fragment_invite_check.xml
  app/src/main/res/layout/fragment_stamps.xml
  app/src/main/res/values/strings.xml
Labels: pull request, chore, ❄️ kldaji

#59 [12-1] 미션 추가 기능 구현 중
  app/src/main/java/com/ariari/mowoori/data/repository/MissionsRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/MissionsRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/missions_add/MissionsAddFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions_add/MissionsAddViewModel.kt
  app/src/main/res/layout/fragment_missions_add.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: fix, pull request, feat, ⛄hyo

#60 [9-1] 새로운 그룹 생성
  app/src/main/java/com/ariari/mowoori/data/repository/GroupRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/GroupRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/data/repository/HomeRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/di/RepositoryModule.kt
  app/src/main/java/com/ariari/mowoori/ui/group/GroupFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/group/GroupViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/register/entity/User.kt
  app/src/main/java/com/ariari/mowoori/util/ToastMessageUtil.kt
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/fragment_group.xml
  app/src/main/res/values/strings.xml
Labels: pull request, feat, 💡light

#61 [13-1, 13-2] 미션 스탬프 화면 구현 및 스탬프 인증/조회 화면 구현
  app/src/main/java/com/ariari/mowoori/data/repository/StampsRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/StampsRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/di/RepositoryModule.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/adapter/StampsAdapter.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/entity/Stamp.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
  app/src/main/res/layout/fragment_stamp_detail.xml
  app/src/main/res/layout/fragment_stamps.xml
  app/src/main/res/layout/item_stamps.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: build, pull request, ❄️ kldaji

#62 [16-1] 구성원 추가 다이얼로그
  app/src/main/java/com/ariari/mowoori/data/repository/MembersRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/MembersRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/di/RepositoryModule.kt
  app/src/main/java/com/ariari/mowoori/ui/group/GroupViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/members/MembersFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/members/MembersViewModel.kt
  app/src/main/java/com/ariari/mowoori/util/ToastMessageUtil.kt
  app/src/main/java/com/ariari/mowoori/widget/BaseDialogFragment.kt
  app/src/main/java/com/ariari/mowoori/widget/InviteDialogFragment.kt
  app/src/main/res/drawable/border_invite_code.xml
  app/src/main/res/drawable/ic_documents.xml
  app/src/main/res/layout/dialog_invite.xml
  app/src/main/res/layout/fragment_members.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feat, 💡light

#63 [13-1] shared element transition 적용
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/adapter/StampsAdapter.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailFragment.kt
  app/src/main/res/layout/fragment_stamp_detail.xml
  app/src/main/res/layout/item_stamps.xml
Labels: pull request, feat, ❄️ kldaji

#64 [4-1] 3단계 눈사람 - 얼굴, 몸통 합체 애니메이션
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/home/entity/ViewInfo.kt
  app/src/main/res/animator/animator_face_down_to_body.xml
  app/src/main/res/animator/animator_face_shape_down.xml
  app/src/main/res/animator/animator_face_shape_reset.xml
  app/src/main/res/animator/animator_face_shape_up.xml
  app/src/main/res/animator/animator_face_up_from_body.xml
  app/src/main/res/drawable/ic_snow_face.xml
  app/src/main/res/drawable/ic_snowman_body.xml
  app/src/main/res/drawable/ic_snowman_button.xml
  app/src/main/res/drawable/ic_snowman_face_2.xml
  app/src/main/res/drawable/ic_snowman_face_3_done.xml
  app/src/main/res/drawable/ic_snowman_face_3_rotate.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: pull request, feat, layout, 🍇yjooooo

#66 [14-1] 스탬프 조회/인증 화면 구현
  app/src/main/java/com/ariari/mowoori/data/repository/MissionsRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/MissionsRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/adapter/StampsAdapter.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/entity/DetailInfo.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/entity/DetailMode.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
  app/src/main/java/com/ariari/mowoori/widget/PictureDialogFragment.kt
  app/src/main/res/drawable/border_sky_blue_f2f6ff_fill_16.xml
  app/src/main/res/drawable/ic_camera.png
  app/src/main/res/drawable/ic_gallery.png
  app/src/main/res/drawable/ic_picture.png
  app/src/main/res/layout/dialog_picture.xml
  app/src/main/res/layout/fragment_stamp_detail.xml
  app/src/main/res/layout/item_stamps.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/strings.xml
Labels: pull request, feat, ❄️ kldaji

#65 [12-1] 미션 생성 유효성 검사, dialog 구현
  app/src/main/java/com/ariari/mowoori/ui/missions_add/MissionsAddFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions_add/MissionsAddViewModel.kt
  app/src/main/java/com/ariari/mowoori/util/BindingAdapters.kt
  app/src/main/java/com/ariari/mowoori/util/Util.kt
  app/src/main/java/com/ariari/mowoori/widget/BaseDialogFragment.kt
  app/src/main/java/com/ariari/mowoori/widget/DatePickerDialogFragment.kt
  app/src/main/java/com/ariari/mowoori/widget/NumberPickerDialogFragment.kt
  app/src/main/res/layout/dialog_date_picker.xml
  app/src/main/res/layout/dialog_number_picker.xml
  app/src/main/res/layout/fragment_missions_add.xml
  app/src/main/res/values-v29/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: fix, pull request, feat, layout, ⛄hyo

#68 3주차 버그 픽스
  app/src/main/java/com/ariari/mowoori/data/repository/HomeRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/res/layout/dialog_picture.xml
Labels: fix, pull request

#69 그룹목록 조회 로직 수정
  app/src/main/java/com/ariari/mowoori/data/repository/HomeRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/home/adapter/DrawerAdapter.kt
  app/src/main/java/com/ariari/mowoori/ui/home/entity/Group.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_stamp_detail.xml
  app/src/main/res/layout/item_drawer_group.xml
Labels: pull request, feat, 💡light

#70 [12-1] 미션 추가 기능 완료
  app/src/main/java/com/ariari/mowoori/data/repository/MissionsRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/MissionsRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/missions_add/MissionsAddFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions_add/MissionsAddViewModel.kt
  app/src/main/res/layout/fragment_missions_add.xml
Labels: fix, pull request, feat, ⛄hyo

#75 테스트 모드 추가
  app/src/main/java/com/ariari/mowoori/data/preference/MoWooriPreference.kt
  app/src/main/java/com/ariari/mowoori/data/preference/MoWooriPreferenceImpl.kt
  app/src/main/java/com/ariari/mowoori/di/DataSourceModule.kt
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterActivity.kt
  app/src/main/res/layout/activity_intro.xml
Labels: pull request, feat, 💡light

#77 [4-1] 애니메이션 관련 코드 HomeFragment로부터 분리, TimberUtil 추상화, 메모리릭 해결
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/home/SnowmanLevel.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowAnimator.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowmanLv2Animator.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowmanLv3Animator.kt
  app/src/main/java/com/ariari/mowoori/ui/missions_add/MissionsAddViewModel.kt
  app/src/main/java/com/ariari/mowoori/util/LogUtil.kt
  app/src/main/java/com/ariari/mowoori/widget/ProgressDialogManager.kt
  app/src/main/res/layout/fragment_home.xml
Labels: pull request, feat, 🍇yjooooo

#78 Feature/23 mission add animation
  app/src/main/java/com/ariari/mowoori/ui/stamp/adapter/StampsAdapter.kt
  app/src/main/res/drawable/ic_eye_black.png
  app/src/main/res/drawable/ic_eye_white.png
  app/src/main/res/drawable/ic_face_empty.png
  app/src/main/res/drawable/ic_intro_mowoori.png
  app/src/main/res/drawable/ic_intro_stamp.png
  app/src/main/res/drawable/ic_intro_title.png
  app/src/main/res/drawable/ic_mouth_oh.png
  app/src/main/res/drawable/ic_mouth_smile.png
  app/src/main/res/drawable/ic_right_hand.png
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/fragment_missions_add.xml
  app/src/main/res/layout/item_stamps.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/xml/activity_intro_xml_constraintlayout_scene.xml
  app/src/main/res/xml/fragment_missions_add_xml_constraintlayout_scene.xml
Labels: pull request, ❄️ kldaji

#79 [20] 테스트 로그인 중복 클릭 방지
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroActivity.kt
Labels: fix, pull request, 💡light

#80 #23 modify: 미션 생성 후 데이터베이스에 저장 방법 수정
  app/src/main/java/com/ariari/mowoori/data/repository/MissionsRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/MissionsRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/missions_add/MissionsAddViewModel.kt
Labels: pull request, modify, 🍇yjooooo

#81 [4-1] 4단계 눈사람 애니메이션 추가
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowmanLv4Animator.kt
  app/src/main/java/com/ariari/mowoori/ui/home/entity/Lv4Component.kt
  app/src/main/res/animator/animator_disappear.xml
  app/src/main/res/animator/animator_hand_show.xml
  app/src/main/res/animator/animator_show_big_heart.xml
  app/src/main/res/animator/animator_show_up.xml
  app/src/main/res/drawable/ic_exclamation.xml
  app/src/main/res/drawable/ic_eye_black.png
  app/src/main/res/drawable/ic_eye_white.png
  app/src/main/res/drawable/ic_face_empty.png
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/drawable/ic_mouth_oh.png
  app/src/main/res/drawable/ic_right_hand.png
  app/src/main/res/drawable/ic_snowman_eye_black_4.xml
  app/src/main/res/drawable/ic_snowman_eye_white_4.xml
  app/src/main/res/drawable/ic_snowman_face_4.xml
  app/src/main/res/drawable/ic_snowman_left_hand_4.xml
  app/src/main/res/drawable/ic_snowman_mouth_oh_4.xml
  app/src/main/res/drawable/ic_snowman_right_hand_4.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/layout_snowman_face_lv4.xml
  app/src/main/res/values/strings.xml
Labels: pull request, feat, ❄️ kldaji

#82 [10-1] '우리'들 목록 조회
  app/src/main/java/com/ariari/mowoori/data/repository/MembersRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/MembersRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/custom/CustomTitleView.kt
  app/src/main/java/com/ariari/mowoori/ui/custom/TitleViewMode.kt
  app/src/main/java/com/ariari/mowoori/ui/members/MembersFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/members/MembersViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/members/adapter/MembersAdapter.kt
  app/src/main/java/com/ariari/mowoori/ui/register/entity/User.kt
  app/src/main/java/com/ariari/mowoori/util/BindingAdapters.kt
  app/src/main/res/drawable/ic_empty.png
  app/src/main/res/drawable/ic_members_profile.xml
  app/src/main/res/drawable/ic_title_view_plus_members.xml
  app/src/main/res/layout/custom_title_view.xml
  app/src/main/res/layout/fragment_members.xml
  app/src/main/res/layout/item_members.xml
  app/src/main/res/values/strings.xml
Labels: pull request, feat, layout, 🍇yjooooo

#83 [10-2] 구성원 추가 초대코드 다이얼로그 수정
  app/src/main/java/com/ariari/mowoori/util/BindingAdapters.kt
  app/src/main/res/layout/dialog_invite.xml
  app/src/main/res/layout/fragment_members.xml
  app/src/main/res/layout/item_members.xml
Labels: pull request, layout, modify, 🍇yjooooo

#84 [14-1] 갤러리 사진 추가가 가능한 스탬프 추가 기능 구현
  app/src/main/java/com/ariari/mowoori/data/repository/StampsRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/StampsRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/di/FirebaseModule.kt
  app/src/main/java/com/ariari/mowoori/di/RepositoryModule.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/adapter/MissionsAdapter.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/entity/Mission.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/entity/MissionInfo.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/adapter/StampsAdapter.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/entity/DetailInfo.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/entity/Stamp.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/entity/PictureType.kt
  app/src/main/java/com/ariari/mowoori/util/Util.kt
  app/src/main/java/com/ariari/mowoori/widget/PictureDialogFragment.kt
  app/src/main/res/layout/dialog_picture.xml
  app/src/main/res/layout/fragment_stamp_detail.xml
  app/src/main/res/layout/fragment_stamps.xml
  app/src/main/res/layout/item_missions.xml
  app/src/main/res/layout/item_stamps.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/strings.xml
Labels: pull request, feat, ⛄hyo

#85 [4-1] 미션 완료 개수에 의존하여 눈사람 애니메이션 실행
  app/src/main/java/com/ariari/mowoori/ui/group/GroupViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowmanLv4Animator.kt
  app/src/main/java/com/ariari/mowoori/ui/home/entity/Group.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/layout_snowman_face_lv4.xml
Labels: pull request, feat, ❄️ kldaji

#87 [10-3] 구성원의 미션리스트 화면으로 이동
  app/src/main/java/com/ariari/mowoori/ui/main/MainActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/members/MembersFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/members/MembersViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/members/adapter/MembersAdapter.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsViewModel.kt
  app/src/main/res/layout/fragment_missions.xml
  app/src/main/res/layout/item_members.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/strings.xml
Labels: pull request, feat, 🍇yjooooo

#88 [5-1] 그룹 선택 어댑터 변경 및 그룹 아이템 배경색 변경
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/home/adapter/DrawerAdapter.kt
  app/src/main/res/layout/fragment_home.xml
Labels: pull request, feat, ❄️ kldaji

#89 [15-1] 미션 인증화면 카메라 기능 구현 및 사용자 권한 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
  app/src/main/java/com/ariari/mowoori/util/Util.kt
  app/src/main/java/com/ariari/mowoori/widget/PictureDialogFragment.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/file_paths.xml
Labels: fix, pull request, feat, chore, ⛄hyo

#90 [21-1] 그룹 간 이동 시 Animation 처리
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowAnimator.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowmanLv3Animator.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowmanLv4Animator.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_stamps.xml
  app/src/main/res/layout/layout_snowman_face_lv4.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: pull request, modify, 🍇yjooooo

#92 [23-1] 앱 로고, 앱 이름 설정
  app/src/main/AndroidManifest.xml
  app/src/main/ic_app_logo-playstore.png
  app/src/main/res/drawable/ic_app_logo_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_app_logo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_app_logo_round.xml
  app/src/main/res/mipmap-hdpi/ic_app_logo.png
  app/src/main/res/mipmap-hdpi/ic_app_logo_foreground.png
  app/src/main/res/mipmap-hdpi/ic_app_logo_round.png
  app/src/main/res/mipmap-mdpi/ic_app_logo.png
  app/src/main/res/mipmap-mdpi/ic_app_logo_foreground.png
  app/src/main/res/mipmap-mdpi/ic_app_logo_round.png
  app/src/main/res/mipmap-xhdpi/ic_app_logo.png
  app/src/main/res/mipmap-xhdpi/ic_app_logo_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_app_logo_round.png
  app/src/main/res/mipmap-xxhdpi/ic_app_logo.png
  app/src/main/res/mipmap-xxhdpi/ic_app_logo_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_app_logo_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo.png
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo_round.png
  app/src/main/res/values/strings.xml
Labels: pull request, chore, 🍇yjooooo

#93 [12-1] 미션 생성 시 인증 횟수 선택 다이얼로그 수정
  app/src/main/java/com/ariari/mowoori/ui/missionsadd/MissionsAddFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missionsadd/MissionsAddViewModel.kt
  app/src/main/java/com/ariari/mowoori/widget/NumberPickerDialogFragment.kt
  app/src/main/res/layout/dialog_number_picker.xml
  app/src/main/res/layout/fragment_missions_add.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: pull request, modify, 🍇yjooooo

#94 [4-1] 백스택에 있는 홈 프래그먼트 접근 시 생기는 애니메이션 이슈 수정
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowmanLv4Animator.kt
Labels: fix, pull request, ❄️ kldaji

#95 [12-1, 21-1] 그룹 간 이동 시 Animation 처리 및 미션 생성 시 미션이름길이 제한 수정
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowmanLv4Animator.kt
  app/src/main/java/com/ariari/mowoori/ui/missionsadd/MissionsAddFragment.kt
  app/src/main/res/layout/fragment_missions_add.xml
  app/src/main/res/values/strings.xml
Labels: fix, pull request, modify, 🍇yjooooo

#96 [15-1] 스탬프 화면 서버통신 구현
  app/src/main/java/com/ariari/mowoori/data/repository/MissionsRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/MissionsRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/custom/CustomTitleView.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/adapter/StampsAdapter.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
  app/src/main/res/layout/fragment_missions.xml
  app/src/main/res/layout/fragment_stamps.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: pull request, feat, ⛄hyo

#97 [4-1] lv4 눈동자 애니메이션 초기 좌표 설정
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowmanLv4Animator.kt
Labels: fix, build, pull request

#98 [5-1] 드로우어 헤더뷰 너비 변경
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_drawer_header.xml
Labels: fix, pull request, ❄️ kldaji

#99 [hotfix] 잘못된 argument 이름 변경
  app/src/main/java/com/ariari/mowoori/ui/main/MainActivity.kt
Labels: fix, pull request, ❄️ kldaji

#101 [13-1] 스탬프 리사이클러뷰 스크롤 시 갱신 문제 해결 및 인증하기 완료 중이라는 로딩화면 추가
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/adapter/StampsAdapter.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
  app/src/main/res/layout/item_stamps.xml
Labels: fix, pull request, feat, 🍇yjooooo

#103 [fix-1] 인증 완료 시 스탬프 숫자 밀리는 버그 해결
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsViewModel.kt
Labels: fix, pull request, ❄️ kldaji

#108 [19-1] Empty View 생성
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/members/MembersFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsFragment.kt
  app/src/main/res/drawable/ic_empty_face.xml
  app/src/main/res/drawable/ic_stamp.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_members.xml
  app/src/main/res/layout/fragment_missions.xml
  app/src/main/res/values/strings.xml
Labels: pull request, feat, ⛄hyo

#113 [14-2] FCM 푸쉬 알림 수신 및 클라이언트에서 FCM post 요청 보내기 버튼으로 임시 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ariari/mowoori/data/local/datasource/MoWooriPrefDataSource.kt
  app/src/main/java/com/ariari/mowoori/data/local/datasource/MoWooriPrefDataSourceImpl.kt
  app/src/main/java/com/ariari/mowoori/data/remote/datasource/FcmDataSource.kt
  app/src/main/java/com/ariari/mowoori/data/remote/datasource/FcmDataSourceImpl.kt
  app/src/main/java/com/ariari/mowoori/data/remote/request/FcmRequest.kt
  app/src/main/java/com/ariari/mowoori/data/remote/response/FcmResponse.kt
  app/src/main/java/com/ariari/mowoori/data/remote/service/FcmService.kt
  app/src/main/java/com/ariari/mowoori/data/repository/IntroRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/IntroRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/data/repository/StampsRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/StampsRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/di/DataSourceModule.kt
  app/src/main/java/com/ariari/mowoori/di/RepositoryModule.kt
  app/src/main/java/com/ariari/mowoori/di/RetrofitModule.kt
  app/src/main/java/com/ariari/mowoori/di/RetrofitServiceModule.kt
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/register/entity/User.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsViewModel.kt
  app/src/main/java/com/ariari/mowoori/util/MowooriMessagingService.kt
  app/src/main/res/layout/fragment_stamps.xml
Labels: pull request, feat, 🍇yjooooo

#114 [fix] 에러 문제 해결
  app/src/main/java/com/ariari/mowoori/data/repository/MissionsRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/MissionsRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/missionsadd/MissionsAddViewModel.kt
  app/src/main/java/com/ariari/mowoori/util/BindingAdapters.kt
  app/src/main/res/drawable/ic_loading.gif
  app/src/main/res/layout/fragment_members.xml
  app/src/main/res/layout/fragment_missions.xml
  app/src/main/res/layout/fragment_missions_add.xml
  app/src/main/res/values/strings.xml
Labels: fix, pull request, ⛄hyo

#122 [25-1] 인트로, 유저 등록 화면 네트워크 연결 확인 및 처리
  app/src/main/java/com/ariari/mowoori/data/repository/IntroRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/IntroRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterViewModel.kt
Labels: pull request, feat, ❄️ kldaji

#123 [14-2] 미션 인증 후 FCM 전송 및 FCM 푸쉬 알림 수신
  app/src/main/java/com/ariari/mowoori/data/remote/request/FcmRequest.kt
  app/src/main/java/com/ariari/mowoori/data/repository/StampsRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/StampsRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/main/MainActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/entity/DetailInfo.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
  app/src/main/java/com/ariari/mowoori/util/LogUtil.kt
  app/src/main/java/com/ariari/mowoori/util/MowooriMessagingService.kt
  app/src/main/res/layout/fragment_stamps.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: pull request, feat, 🍇yjooooo

#124 [fix] 머지 후 생긴 문제 해결
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
Labels: fix, pull request, 🍇yjooooo

#125 [25-1] 네트워크 에러 메세지 추가
  app/src/main/java/com/ariari/mowoori/data/repository/MembersRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/members/MembersViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
  app/src/main/java/com/ariari/mowoori/util/ErrorMessage.kt
Labels: pull request, feat, ❄️ kldaji

#128 [14-2] FCM 서버키 Firebase에서 가져온 후 EncryptedSharedPreferences에 저장, FCM Post 통신 시 헤더 설정 인터셉터가 하도록 수정
  app/src/main/java/com/ariari/mowoori/data/local/datasource/MoWooriPrefDataSource.kt
  app/src/main/java/com/ariari/mowoori/data/local/datasource/MoWooriPrefDataSourceImpl.kt
  app/src/main/java/com/ariari/mowoori/data/remote/service/FcmService.kt
  app/src/main/java/com/ariari/mowoori/data/repository/IntroRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/IntroRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/di/RetrofitModule.kt
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
Labels: pull request, feat, 🍇yjooooo

#129 [25-1] 네트워크 에러 핸들링
  app/src/main/java/com/ariari/mowoori/MoWooriApp.kt
  app/src/main/java/com/ariari/mowoori/data/repository/GroupRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/GroupRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/data/repository/IntroRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/data/repository/MembersRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/data/repository/MissionsRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/data/repository/StampsRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/group/GroupFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/group/GroupViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/members/MembersViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/missionsadd/MissionsAddViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
  app/src/main/java/com/ariari/mowoori/util/ErrorMessage.kt
Labels: pull request, feat, ❄️ kldaji

#131 [fix] 그룹 초대 코드 및 그룹 이름 유효성 확인
  app/src/main/java/com/ariari/mowoori/ui/group/GroupFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/group/GroupViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/missionsadd/MissionsAddFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailFragment.kt
  app/src/main/java/com/ariari/mowoori/util/ExtensionUtil.kt
  app/src/main/res/animator/animator_invalid_vibrate.xml
  app/src/main/res/layout/fragment_group.xml
  app/src/main/res/values/strings.xml
Labels: fix, pull request, ❄️ kldaji

#133 [14-2] FCM 반복 post요청 비동기로 수정
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
Labels: pull request, feat, 🍇yjooooo

#138 [fix] 스탬프 상세화면 에러 수정
  app/build.gradle
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailFragment.kt
  build.gradle
Labels: fix, build, pull request, ⛄hyo

#139 [fix] 세로모드 고정 및 홈화면의 알림메뉴 주석 처리
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/res/menu/tb_home_menu.xml
Labels: fix, pull request, 🍇yjooooo

#141 [fix] 홈 화면 눈내리는 시작 속도 및 햄버거 아이콘 수정
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowAnimator.kt
  app/src/main/res/drawable/ic_hamburger.xml
Labels: fix, pull request, ⛄hyo

#143 [fix] 리사이클러뷰 overscrollmode 설정 및 드로우어 레이아웃 리사이클러뷰 영역 수정
  app/src/main/res/drawable/border_sky_blue_line_oval.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_members.xml
  app/src/main/res/layout/fragment_missions.xml
  app/src/main/res/layout/fragment_notification.xml
  app/src/main/res/layout/fragment_stamps.xml
Labels: fix, pull request, 🍇yjooooo

#144 [fix] BottomNavigation 선택 시 ripple color 설정
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: fix, pull request, 🍇yjooooo

#145 [fix] 미션 인증 코멘트 유효성 검사 추가
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/missionsadd/MissionsAddFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
  app/src/main/java/com/ariari/mowoori/util/Util.kt
  app/src/main/res/drawable/ic_red_circle.xml
  app/src/main/res/layout/fragment_stamp_detail.xml
  app/src/main/res/values/strings.xml
Labels: fix, pull request, feat, ⛄hyo

#146 [fix] 미션 리스트화면 그룹 유무에 따라 상단 타이틀뷰 미션 추가 버튼, 뒤로가기 버튼 설정
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsViewModel.kt
  app/src/main/res/drawable/ic_app_logo_background.xml
  app/src/main/res/layout/fragment_missions.xml
  app/src/main/res/values/strings.xml
Labels: fix, pull request, 🍇yjooooo

#148 [fix] 로그인 전 네트워크 오류 시 앱 종료 및 그룹 & 닉네임 중복 검사
  app/src/main/java/com/ariari/mowoori/data/repository/GroupRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/GroupRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/data/repository/IntroRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/IntroRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/group/GroupFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/group/GroupViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterViewModel.kt
  app/src/main/java/com/ariari/mowoori/util/ErrorMessage.kt
  app/src/main/java/com/ariari/mowoori/util/InvalidMode.kt
  app/src/main/res/layout/fragment_group.xml
  app/src/main/res/xml/fragment_group_xml_constraintlayout_scene.xml
Labels: fix, pull request, ❄️ kldaji

#150 [fix] 눈내리는 애니메이션이 그룹 변경될때마다 멈추는 이슈 해결
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowAnimator.kt
Labels: fix, pull request, 🍇yjooooo

#152 [14-3] 스탬프판 완성 시 doneMission 추가 작업 구현
  app/src/main/java/com/ariari/mowoori/data/repository/StampsRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/StampsRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
  app/src/main/java/com/ariari/mowoori/util/ErrorMessage.kt
Labels: pull request, feat, ⛄hyo

#154 [fix] FCM 알림 클릭 후 앱 열었을 시 상세 정보 안뜨는 에러 해결
  app/src/main/java/com/ariari/mowoori/ui/main/MainActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
  app/src/main/res/layout/activity_intro.xml
Labels: fix, pull request, 🍇yjooooo

#156 [fix] 콜백지옥 제거
  app/src/main/java/com/ariari/mowoori/data/local/datasource/MoWooriPrefDataSource.kt
  app/src/main/java/com/ariari/mowoori/data/local/datasource/MoWooriPrefDataSourceImpl.kt
  app/src/main/java/com/ariari/mowoori/data/repository/GroupRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/GroupRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/data/repository/IntroRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/data/repository/MissionsRepository.kt
  app/src/main/java/com/ariari/mowoori/data/repository/MissionsRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/group/GroupFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/group/GroupViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/members/MembersFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/members/MembersViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/missionsadd/MissionsAddFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missionsadd/MissionsAddViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
  app/src/main/java/com/ariari/mowoori/util/DuplicatedException.kt
  app/src/main/res/layout/fragment_stamps.xml
Labels: fix, pull request, ❄️ kldaji

#161 [fix] Animator 클래스에 뷰모델 넘기는부분 삭제
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowAnimator.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowmanLv2Animator.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowmanLv3Animator.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowmanLv4Animator.kt
Labels: fix, pull request, 🍇yjooooo

#162 [fix] '우리'들 탭에서 자기 자신의 프로필은 안보이도록 수정
  app/src/main/java/com/ariari/mowoori/ui/members/MembersViewModel.kt
Labels: fix, pull request, 🍇yjooooo

#164 [fix] 로딩뷰 제거
  app/src/main/java/com/ariari/mowoori/base/BaseFragment.kt
  app/src/main/java/com/ariari/mowoori/data/remote/request/FcmRequest.kt
  app/src/main/java/com/ariari/mowoori/data/repository/StampsRepositoryImpl.kt
  app/src/main/java/com/ariari/mowoori/ui/members/MembersFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/missionsadd/MissionsAddFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/adapter/StampsAdapter.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/entity/DetailInfo.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/entity/Stamp.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
  app/src/main/java/com/ariari/mowoori/util/MowooriMessagingService.kt
  app/src/main/res/layout/fragment_stamps.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: fix, pull request, ❄️ kldaji

#165 [fix] FCM으로 앱 켰을 경우 popBackStack으로 Home 돌아왔을 때 Lv3, Lv4애니메이션 위치 틀어지는 문제 해결
  app/src/main/java/com/ariari/mowoori/ui/home/HomeFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowAnimator.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowmanLv2Animator.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowmanLv3Animator.kt
  app/src/main/java/com/ariari/mowoori/ui/home/animator/SnowmanLv4Animator.kt
  app/src/main/java/com/ariari/mowoori/ui/main/MainActivity.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailFragment.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: fix, pull request, 🍇yjooooo
