Repository boostcampwm-2021/android02-mowoori, pull requests merged in 2021-12, with the labels that each got.

#166 [fix] 홈화면 인사말 추가 및 테스트 계정 코드 주석 처리
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroActivity.kt
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: fix, pull request, feat, 🍇yjooooo

#168 #167 fix: 그룹 가입 시 멘트 수정 및 미션 프래그먼트 트랜지션 에러 수정
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailFragment.kt
  app/src/main/res/layout/fragment_group.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_invite_check.xml
  app/src/main/res/values/strings.xml
Labels: fix, pull request, 🍇yjooooo

#170 [fix] Exception Catch 위치 변경
  app/src/main/java/com/ariari/mowoori/ui/group/GroupViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/home/HomeViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/intro/IntroViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/members/MembersFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/members/MembersViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/missions/MissionsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/missionsadd/MissionsAddViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/register/RegisterViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsFragment.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp/StampsViewModel.kt
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailViewModel.kt
  app/src/main/res/layout/fragment_home.xml
Labels: fix, pull request, ❄️ kldaji

#171 #159 fix: PictureDialogFragment 생성자 삭제 후 setFragmentResultListener 설정
  app/build.gradle
  app/src/main/java/com/ariari/mowoori/ui/stamp_detail/StampDetailFragment.kt
  app/src/main/java/com/ariari/mowoori/widget/PictureDialogFragment.kt
  build.gradle
Labels: fix, pull request, 🍇yjooooo
